from app import db, flask_bcrypt


class Category(db.Model):
    """ User Model for storing user related details """
    __tablename__ = "scm_hd_category"

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    lvl = db.Column(db.Integer)
    itemCsfCd = db.Column(db.String(8))
    itemCsfNm = db.Column(db.String(100))
    highItemCsfCd = db.Column(db.String(8))
    useYn = db.Column(db.String(1), default='Y')
    itemCsfGbcd = db.Column(db.String(2), default='40')
    itemCsfGbcdNm = db.Column(db.String(100))
    itemCsfLvl = db.Column(db.String(1))
    osbd = db.Column(db.Integer)
    sizeCsfGbcd = db.Column(db.String(4))
    sizeCsfGbcdNm = db.Column(db.String(100))
    qaTrgtYn = db.Column(db.String(1), default='N')
    safeCertTrgtYn = db.Column(db.String(1), default='N')
    safeCertTypeGbcd = db.Column(db.String(2))
    coreMngYn = db.Column(db.String(1), default='N')
    itstDlbrYn = db.Column(db.String(1), default='N')
    infNotfBsicCd = db.Column(db.String(3))
    infNotfBsicNm = db.Column(db.String(100))
    hdmalPntAcmRate = db.Column(db.Integer)
    hdmalPntAcmRateUseYn = db.Column(db.String(1), default='N')
    dluMaxBuyQty = db.Column(db.Integer)
    yruMaxBuyQty = db.Column(db.Integer)
    qaCsfCd = db.Column(db.String(3))
    qaCsfNm = db.Column(db.String(100))
    itemPupUseYn = db.Column(db.String(1), default='N')
    frdlvSellLimtYn = db.Column(db.String(1), default='N')
    imdtCnclPossYn = db.Column(db.String(1), default='N')
    itemTaxnGbcd = db.Column(db.String(3))
    custMskExcpProcYn = db.Column(db.String(1), default='N')
    hscd = db.Column(db.String(10))
    itemCsfCdL = db.Column(db.String(8))
    itemCsfCdM = db.Column(db.String(8))
    itemCsfCdS = db.Column(db.String(8))
    itemCsfCdD = db.Column(db.String(8))
    itemCsfNmL = db.Column(db.String(100))
    itemCsfNmM = db.Column(db.String(100))
    itemCsfNmS = db.Column(db.String(100))
    itemCsfNmD = db.Column(db.String(100))
    storpiupPossYn = db.Column(db.String(1), default='N')
    cvstDlvYn = db.Column(db.String(1), default='N')
    subwDlvYn = db.Column(db.String(1), default='N')
