from app import db, flask_bcrypt


class JDOrder(db.Model):
    """ User Model for storing user related details """
    __tablename__ = "scm_jd_orders"

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    orderId = db.Column(db.String(15))
    vendorId = db.Column(db.String(10))
    orderType = db.Column(db.String(2))
    payType = db.Column(db.String(1))
    orderTotalPrice = db.Column(db.String(12))
    orderSellerPrice = db.Column(db.String(12))
    orderPayment = db.Column(db.String(12))
    freightPrice = db.Column(db.String(12))
    sellerDiscount = db.Column(db.String(12))
    orderState = db.Column(db.String(30))
    orderStateRemark = db.Column(db.TEXT)
    deliveryType = db.Column(db.String(1))
    invoiceInfo = db.Column(db.TEXT)
    invoiceCode = db.Column(db.String(20))
    orderRemark = db.Column(db.String(20))
    orderStartTime = db.Column(db.String(20))
    orderEndTime = db.Column(db.String(20))
    venderRemark = db.Column(db.String(20))
    balanceUsed = db.Column(db.String(12))
    pin = db.Column(db.String(20))
    returnOrder = db.Column(db.String(12))
    paymentConfirmTime = db.Column(db.String(20))
    wayBill = db.Column(db.String(10))
    logisticsId = db.Column(db.String(2))
    modified = db.Column(db.String(20))
    directParentOrderId = db.Column(db.String(15))
    parentOrderId = db.Column(db.String(15))
    customs = db.Column(db.String(20))
    customsModel = db.Column(db.String(20))
    orderSource = db.Column(db.String(20))
    storeOrder = db.Column(db.String(20))
    ipSopShipmenttype = db.Column(db.Integer)
    scDT = db.Column(db.String(20))
    serviceFee = db.Column(db.String(12))
    taxFee = db.Column(db.String(12))
    tuiHuoWuYou = db.Column(db.String(20))
    orderSign = db.Column(db.String(30))
    storeId = db.Column(db.String(20))
    realPin = db.Column(db.String(20))
    declarationStatus = db.Column(db.String(1))
    declarationDesc = db.Column(db.TEXT)
    open_id = db.Column(db.String(10))
    open_id_buyer = db.Column(db.String(20))

